### PR TITLE
Update BSC.json

### PR DESCRIPTION
**Pull request by Densito78**
Adding STAKE ON BSC

### CODE REVIEW

**Comment by Densito78** [comment]
@H3xept, can you merge, please?

**Comment by chybisov** [comment]
@Densito78 doesn't look legit to me 🙂

**Comment by Densito78** [comment]
> @Densito78 doesn't look legit to me 🙂

@chybisov why, this is not scam token

**Comment by chybisov** [comment]
> > @Densito78 doesn't look legit to me 🙂
> 
> @chybisov why, this is not scam token

Could you please provide more evidence? At first look, this contract address has no liquidity and volume. Also not listed on coingecko or coinmarketcap

**Pull request closed without merging**
